language: node_js
node_js:
  - 10
  - 12
  - 14

script:
  - npm run build
  - npm run lint
  - npm run format -- --check --write false
  - echo -n react-layout-components.js.org > ./build/CNAME

deploy:
  - provider: pages:git
    edge: true
    local_dir: ./build/
    keep_history: false
    on:
      branch: main
      node_js: 12
